### ISSUE TITLE
Got 404 page not found

### ISSUE THREAD

**Issue by jerrywoo96** [G-M0N3Y-2503/mega-get-server#1] opened 2021-03-21 08:24 UTC
I cannot access the web interface at 192.168.1.247:8080.
I'm using a macvlan interface such that it acts like the container is directly connected to my lan network, so i do not need to forward any ports in the host.

I'm using docker compose to spin up the container. Here are the configs.

    MegaGetServer:
        container_name: MegaGetServer
        image: gm0n3y2503/mega-get-server:latest
        restart: always
        user: "0"
        dns: 192.168.1.254
        environment:
            EXTERNAL_HOST: 192.168.1.247
            NEW_FILE_PERMISSIONS: 777
            NEW_FOLDER_PERMISSIONS: 777
        networks:
            macvlan:
                ipv4_address: 192.168.1.247
        volumes:
            - /volume1/Server/Downloads/MegaGetServer:/data

Here are the logs

Sun, 21 Mar 2021 08:12:49 +0000 | INFO   | server     |  | Serving using application   : /home/mega/websocket.sh ,
Sun, 21 Mar 2021 08:12:49 +0000 | INFO   | server     |  | Starting WebSocket server   : ws://879ea96031b0:8080/,
[Initiating server in background. Log: /home/mega/.megaCmd/megacmdserver.log],
Warning: unable to get locale ,
Warning: unable to get locale ,
Another instance of MEGAcmd Server is running. Execute with --skip-lock-check to force running (NOT RECOMMENDED),
,
.===========================================================================.,
|               __  __ _____ ____    _                      _               |,
|              |  \/  | ___|/ ___|  / \   ___ _ __ ___   __| |              |,
|              | |\/| | \  / |  _  / _ \ / __| '_ ` _ \ / _` |              |,
|              | |  | | /__\ |_| |/ ___ \ (__| | | | | | (_| |              |,
|              |_|  |_|____|\____/_/   \_\___|_| |_| |_|\__,_|              |,
|                                                                           |,
|                                  SERVER                                   |,
`===========================================================================´,
Default files permissions: 777,
Default folders permissions: 777,
Sun, 21 Mar 2021 08:13:05 +0000 | ACCESS | http       | url:'http://192.168.1.247:8080/mega-get.html' | NOT FOUND,
Sun, 21 Mar 2021 08:14:54 +0000 | ACCESS | http       | url:'http://192.168.1.247:8080/' | NOT FOUND,

**Comment by jerrywoo96** [comment] 2021-03-21 08:25
My host does not have MEGAcmd installed.

**Comment by jerrywoo96** [comment] 2021-03-21 08:28
![image](https://user-images.githubusercontent.com/26324139/111898641-54db0500-8a62-11eb-9283-a000339ba8b7.png)
![image](https://user-images.githubusercontent.com/26324139/111898651-658b7b00-8a62-11eb-9e6e-9282e2bde70e.png)

**Comment by G-M0N3Y-2503** [comment] 2021-03-21 09:45
This image was designed to be used via NAS, which means that no files are (at least currently) served via HTTP/S.
The "web" interface is just a HTML file that connects to the container via a WebSocket.
In your case, it looks like the file will be located at `/volume1/Server/Downloads/MegaGetServer/mega-get.html`.

If `/volume1/Server` is shared via NAS at `192.168.1.247/share` you could access it with the `file://` protocol at `file://192.168.1.247/share/Downloads/MegaGetServer/mega-get.html`

**Comment by jerrywoo96** [comment] 2021-03-21 13:21
So if i am right, i double click the html to be opened in a web browser, the html file will communicate with the websocket server at 192.168.1.247:8080?

**Comment by jerrywoo96** [comment] 2021-03-21 13:29
And i can host the html file in a http server as long as the address configured for the websocket in the html file can communicate with the server eg. 192.168.1.247:8080 yup?

**Comment by G-M0N3Y-2503** [comment] 2021-04-03 01:44
Correct, The important part Is that you can access the WebSocket from wherever the HTML file is served.

Serving the HTML from this container isn't something I am considering right now and it looks like you got your issue sorted. 
So I'll close this issue.

**Closed as completed by G-M0N3Y-2503** 2021-04-03 01:44 UTC

**Comment by jerrywoo96** [comment] 2022-02-27 06:58
I figured this may help you run both the html file together with the web socket, so users would not have to navigate to the directory to open the file or run 2 seperate containers. Hope you can integrate this into your existing dockerfile :). Thanks for the docker image :D

files/nginx.conf:
```
events {
}

http {
	index index.html;
	server {
		listen 80; # expose a port different from websocket
		location / {
			root /usr/share/nginx/html;
		}
	}
}

```

Dockerfile:
```
FROM nginx:alpine
COPY files/nginx.conf /etc/nginx/nginx.conf

# do the copy after replacing the url from the environment.
COPY files/mega-get.html /usr/share/nginx/html/index.html

# expose nginx port
EXPOSE 80

```

**Comment by G-M0N3Y-2503** [comment] 2022-05-10 11:58
might not be as robust as `nginx` but `v1.4.0` might interest you.
